/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/personagem_menino.glb --typescript 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/personagem_menino.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.046, -0.168, 0]} scale={[1.037, 1, 1]}>
        <mesh geometry={nodes.Cube.geometry} material={materials.Materiais} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials['Cabelo.001']} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Cabelo.001']} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials['Cabelo.001']} />
      </group>
      <mesh geometry={nodes.Corpo.geometry} material={materials.Materiais} position={[-0.01, 2.876, 0]} scale={[1.037, 1, 1]} />
      <mesh geometry={nodes.Orelha.geometry} material={materials.Materiais} position={[0.791, 3.384, 0.074]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Mãos.geometry} material={materials.Materiais} position={[-0.046, -0.927, -0.974]} rotation={[0.004, 0, 0.003]} />
      <mesh geometry={nodes.NurbsPath084.geometry} material={materials['Cabelo.001']} position={[0.472, 3.201, -0.444]} rotation={[0, -1.422, -Math.PI / 2]} scale={-0.061} />
    </group>
  )
}

useGLTF.preload('/personagem_menino.glb')
